image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/aqa-shop.jar &
  - chmod +x gradlew

build_script:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sleep 20
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar
  - java -Dspring.datasource-postgresql.url=jdbc:postgresql://localhost:5432/app -jar artifacts/aqa-shop.jar
  - ./gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/app
  - ./gradlew clean test -Ddb.url=jdbc:postgresql://localhost:5432/postgres